version: "3.9"
services:

  fastapi:
    image: ghcr.io/etunednd/etune-discord-bot:main
    restart: always
    ports:
      - "5000:80"

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - "5001:8080"

volumes:
  postgres_data:
    external: true